service: p-appointment-scheduler
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  environment:
    APPOINTMENTS_TABLE: ${self:service}-appointments-${self:provider.stage}
    API_KEY: test-api-key
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:DeleteItem
            - dynamodb:UpdateItem
            - dynamodb:Query
          Resource: 
            - Fn::GetAtt: [AppointmentsTable, Arn]
            - Fn::Join:
              - "/"
              - - Fn::GetAtt: [AppointmentsTable, Arn]
                - "index/*"

functions:
  appointmentScheduler:
    handler: src/handler.appointmentScheduler
    events:
      - httpApi:
          path: /appointments
          method: post
  deleteAppointment:
    handler: src/handler.deleteAppointment
    events:
      - httpApi:
          path: /appointments/{id}
          method: delete

resources:
  Resources:
    AppointmentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-appointments-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: appointmentId
            AttributeType: S
          - AttributeName: locationId
            AttributeType: S
          - AttributeName: appointmentDateTime
            AttributeType: S
        KeySchema:
          - AttributeName: appointmentId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: locationTime
            KeySchema:
              - AttributeName: locationId
                KeyType: HASH
              - AttributeName: appointmentDateTime
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
